### ISSUE TITLE
Try

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#1]
I try to see If I understand how to use this

**Comment by cdparra** [comment]
@LucileMP you can use issues to describe problems or even ideas you have for AppCivist. 

On the right side, you should see a link entitle **Labels** (see pic below) that if you click, you will see the available labels we will use. 
![image](https://cloud.githubusercontent.com/assets/630150/25398288/6efd1058-29b9-11e7-804b-96badb01f5d6.png)

Choose Nouvelle Aquitaine to indicate this is coming from that pilot. You can add multiple labels, so you can also determine how important is something by choosing URGENT, NO RUSH or SMALL RUSH. 

Someon in the team (most likely me) will respond by either commenting or transforming this issue into more specific issues in one of the following repositories, where the code actually resides: 

* [appcivist-platform](https://github.com/socialappslab/appcivist-platform) 
* [appcivist-pb-client](https://github.com/socialappslab/appcivist-pb-client)
* [appcivist-voting-api](https://github.com/socialappslab/appcivist-voting-api) 
* [appcivist-notification-service](https://github.com/socialappslab/appcivist-notification-service)

Once the issue has been resolved, we will close the issue

**Comment by cdparra** [comment]
BTW @LucileMP:  
* if what you are describing is an idea for something new, use the label "feature request". 
* If what you are describing is an idea to improve something that already exists in appcivist, use the label "enhancement" 
* If what you are describing is an error or problem with existing features, use the label "help wanted"

**Comment by LucileMP** [comment]
Perfect !

But I don’t have the logo next to labels in my page, that is why I can’t add a label.

Do you have an idea why I do not have this ? Maybe it is a configuration account issue;

Thanks,

Lucile

De : Cristhian Parra [mailto:notifications@github.com]
Envoyé : mardi 25 avril 2017 19:21
À : socialappslab/appcivist <appcivist@noreply.github.com>
Cc : Lucile Fauviaux <lucile.fauviaux@missionspubliques.com>; Mention <mention@noreply.github.com>
Objet : Re: [socialappslab/appcivist] Try (#1)


@LucileMP<https://github.com/LucileMP> you can use issues to describe problems or even ideas you have for AppCivist.

On the right side, you should see a link entitle Labels (see pic below) that if you click, you will see the available labels we will use.
[image]<https://cloud.githubusercontent.com/assets/630150/25398288/6efd1058-29b9-11e7-804b-96badb01f5d6.png>

Choose Nouvelle Aquitaine to indicate this is coming from that pilot. You can add multiple labels, so you can also determine how important is something by choosing URGENT, NO RUSH or SMALL RUSH.

Someon in the team (most likely me) will respond by either commenting or transforming this issue into more specific issues in one of the following repositories, where the code actually resides:

  *   appcivist-platform<https://github.com/socialappslab/appcivist-platform>
  *   appcivist-pb-client<https://github.com/socialappslab/appcivist-pb-client>
  *   appcivist-voting-api<https://github.com/socialappslab/appcivist-voting-api>
  *   appcivist-notification-service<https://github.com/socialappslab/appcivist-notification-service>

Once the issue has been resolved, we will close the issue
