### ISSUE TITLE
AppCivist is not working with some browsers

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#10]
Hey Christian, 

For LNA, as Tifenn reported, the platform is not working on some browsers (Mozilla Firefox, Internet Explorer). It is quit problematic because a lot of administrations are using Mozilla here in France. I know that it is complicated to solve this issue, because it is more related to the fact that those browsers are not as good as Chrome, but do you think there is a way to improve this ? 

Also, Tifenn said that it was not working with Safari, but she misleaded, and was thinking of Firefox I guess. We did not have the chance to use the platform with Safari, because no one is using Mac's at the office or in the French administrations.

**Comment by cdparra** [comment]
@LucileMP I have tested the platform both in Firefox and Safari. Both working well on my tests. Explorer is the one that is not yet supported. 

Can you elaborate more on what specifically you found that it is not working?

**Comment by cdparra** [comment]
@LucileMP in our tests, the app is working well in both safari and Firefox. We need you to clarify the following: 
- Which browser are you experimenting problems with? 
- What specific feature is causing problems? 

Otherwise, we can simply consider this issue as done.

**Comment by cdparra** [comment]
@LucileMP, this is Internet Explorer. Internet Explorer is the only browser we do not support. How many people are using IE? Is there a reason that prevents them from using either Chrome or Firefox?

**Comment by LucileMP** [comment]
In french adminstations, it is impossible to install new stuff on a computer without the approuval of the tech departement. Most of the administrations are using IE or Firefox because they do not want to give their data to google. 
If the want to install Chrome, they need to ask to the tech departement, and have a political approval, and it can be tricky and very long. 

That is why it is really important that the platform can be used on differents browsers :)

**Comment by cdparra** [comment]
@LucileMP AppCivist works for Chrome, Safari and Firefox. It only does not work for Internet Explorer (please, bare in mind that we are still an alpha prototype heavily in development). 

Until we get support for internet explorer, I suggest they use Firefox if that's what they have installed. We have tested with the latest firefox version (for Mac OSX) and it works well, but it might be that they have problems with their specific version and OS, so can you or Tifenn report back to us to let us know if they find any issue with the specific version of Firefox they have installed. 

In this report, please include some details from the error console in the browsers they use: 

**How to open the console in internet explorer** 
1. Start it by opening the F12 developer tools, and selecting the Console tool (CTRL + 2). 
2. You can also open the Console within another tool using the Show console button in the upper-right of the tools pane or CTRL + `. 

You should see something like the following. Only then load the app and send us a screenshot to see the errors
![image](https://user-images.githubusercontent.com/630150/28133043-aa3b5270-670c-11e7-97a8-269347676c45.png)

**How to open the console in Firefox, Chrome, and Safari** 
1. Visit AppCivist
2. Right click anywhere in the website and choose "Inspect Element"
3. Go to the tab "Console"

**Comment by LucileMP** [comment]
I understand that it is a beta version, do not worry :)
I just let you know this in order for you to know that for French pilots and users it is important in the future to work on the accessibility with those broswers. 

I will try to see if I can have them test the process you explain.
