### ISSUE TITLE
Status indicator message for Proposta Publicada

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#106]
1.  Change menu text from "Proposta"  = >  "Proposta Publicada"  
That is the name in all instructions so we should use it here.

2.  Change message for Proposta Publicada to
"Tem certeza de que deseja tornar o seu Rascunho em Proposta Publicada agora?  Essa ação não poderá ser desfeita.  Se esta proposta é compartilhada com outros, é essencial consultá-los para verificar se concordam.

Publicada significa que toda a comunidade universitária pode ver e comentar mas ninguém pode mais editar. Uma vez publicada, a proposta passará automaticamente para a Assembleia Intercampi Editorial para ser incluida na próxima fase."

**Comment by cdparra** [comment]
@jamesholston what do you mean by `menu text`? What's the menu text for you? Can you provide a screenshot? 

If you are referring to the word used in the dropdown options to change the statu, then that's simply the name of the status itself, which is `Published` and is translated as `Publicada`, as in the other cases. I would avoid using too many words. I think everybody knows in this page that we are talking about a `Proposal`, so most likely, we don't need to use that word again.
