### ISSUE TITLE
Different issues 

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#11]
Hey Christian, 

I do not know what happen but a lot of stuff are not working anymore on the LNA platform :

- [x] Proposals do not appear in the working group anymore

- [x] When clicking on "add a new" in the working group - nothing happen 

- [x] In the campaign, there is now a button "Ajouter une idée - add an idea" - it is not correct because we do not have idea in LNA - and when clicking on it, the fill is in english and not translated

- [x] Under research, you have propositions and my proposlas which need to be translated

**Comment by LucileMP** [comment]
We really need those issues to be solve by monday evening, a group is meeting on the 13th of June and they really need it.

**Comment by cdparra** [comment]
I will take a look on Sunday @LucileMP. Until then I will be traveling. If @jorgeramirez has some time during the weekend, he will take a look too.

**Comment by jorgeramirez** [comment]
Commit https://github.com/socialappslab/appcivist-pb-client/commit/6bf8eba04f7a92231c0eac94a6abd713c31fdc7e solves proposals not showing in WG dashboard.

**Comment by LucileMP** [comment]
Ok ! Thanks for solving this issue, it was the most urgent one :)

**Comment by cdparra** [comment]
Commit https://github.com/socialappslab/appcivist-pb-client/commit/8a93c5fd2060a1f9dd4778fd1c00a9bb3dcf06a0 should fix the third issue

**Comment by cdparra** [comment]
Additional fixes on https://github.com/socialappslab/appcivist-pb-client/commit/59b15d20917ee8a97258e9b1709d34adcbd682bb

**Comment by cdparra** [comment]
Last issue fixed in https://github.com/socialappslab/appcivist-pb-client/commit/fd71dabc6d0eb98ef7cc71e4d3bc60265553d374

@LucileMP can you confirm all is working now?

**Comment by cdparra** [comment]
Also, @LucileMP I suggest you clear your browser's cache to make sure you get the latest version we just published on our servers

**Comment by LucileMP** [comment]
Thanks, it is working ! I will come back to you with other comments and ideas from the meeting that I had with LNA last week, it was intersting ! 
And I will not be able to join tonight, so do not wait for me !
Thanks @cdparra
