### ISSUE TITLE
Email verification translations

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#114]
The second issue with the email verification concerns language and translations:
2.1  The email confirmation message sent to user is in English, even though the user language is set to Portuguese.  Change to correspond to user language choice.  If not possible, change to Portuguese.  Also the user name appears twice.

=> Olá "username",
Para confirmar seu endereço de e-mail, clique no  [link]

Saudações,
Equipe PPI Unifesp-AppCivist

![tela teste 1](https://user-images.githubusercontent.com/5572598/42240367-6d1cf698-7edd-11e8-9866-691145a008f1.png)

2.2.  Change "Seu email foi atualizado. Verifique sua caixa de entrada de e-mail quando possível para verificar sua validade."  =>  "Seu e-mail foi atualizado.  Você receberá uma mensagem neste e-mail para confirmar.

![image001](https://user-images.githubusercontent.com/5572598/42240182-db65f16e-7edc-11e8-87c4-e12510b6c165.png)

2.3  Change link confirmation message on https://platform.appcivist from "... verificado com sucesso."  to
=>  "... confirmado com sucesso."

![tela confirmacao](https://user-images.githubusercontent.com/5572598/42240838-05fa5e7c-7edf-11e8-815e-a5bcdc86dbb4.png)

**Comment by cdparra** [comment]
This is now part of epic #113
