### ISSUE TITLE
Logout from Minhas Configurações in production site goes to wrong URL, in some cases

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#115]
On my MacBook Pro, in Chrome, logout from profile page (Minhas Configurações) in production STILL goes to wrong URL.  In testing, however, logout from profile is correct, going to assembly page.  Did it not push to production, or push incorrectly?

<img width="1440" alt="screen shot 2018-07-03 at 4 47 42 pm" src="https://user-images.githubusercontent.com/5572598/42241569-66882d4e-7ee1-11e8-877d-72670fe75476.png">

HOWEVER, in Cláudia's account, on her desktop, in Chrome, logout from profile page is correct:

![image-1](https://user-images.githubusercontent.com/5572598/42242213-81ce7fca-7ee3-11e8-9e8e-dd5a96280d8b.png)

**Comment by cdparra** [comment]
This was not included in the last sprint. It is part of the current sprint. See https://github.com/socialappslab/appcivist-pb-client/issues/1249

**Comment by jamesholston** [comment]
Actually, I think it is working.  I cleared my cache and logging out from profile page went to assembly page correctly
