### ISSUE TITLE
Email verification modal behaving erratically

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#116]
1.  Both Claudia and I have received the email confirmation message below twice upon login.  Each time we have clicked "yes".   After the second time, we have not received it again.

![screen shot 2018-06-29 at 3 32 22 pm](https://user-images.githubusercontent.com/5572598/42242933-10de376c-7ee6-11e8-90d3-4f8a0cf169eb.png)
 
2.  Neither Claudia nor I has received an email with a confirmation link.  This is correct because neither of us had changed our addresses.  They were already correct and we merely confirmed it.  However, Claudia's profile page shows the message in green that her email was updated (which is wasn't) and that she will receive a confirmation email (which she didn't).  This green message remains on her profile page even after repeatedly logging out and in.  This message has never appeared on my profile page!!!

<img width="1440" alt="screen shot 2018-07-03 at 5 21 43 pm" src="https://user-images.githubusercontent.com/5572598/42243343-6a491262-7ee7-11e8-96ca-0fd5cf88d3a2.png">

3.  Alisson's account shows the same green verification message on his profile page as Claudia's, even though he only confirmed that his email was correct (as in case of Claudia and me):

<img width="1440" alt="screen shot 2018-07-03 at 5 45 31 pm" src="https://user-images.githubusercontent.com/5572598/42243967-76c505b2-7ee9-11e8-8838-747be8b6f6cf.png">

**Comment by cdparra** [comment]
This was broken in two issues that are now part of EPIC #113
