### ISSUE TITLE
Change status to Public Draft in production site does not work

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#117]
Change status to Public Draft in production site does not work.  Even when all the custom fields are filled in, changing the status from Private to Public Draft returns the error message below.  As this change of status was supposed to be available on July 1, I marked this issue "critical."

<img width="1440" alt="screen shot 2018-07-03 at 7 11 50 pm" src="https://user-images.githubusercontent.com/5572598/42246944-008747fa-7ef5-11e8-9fab-b9b581807f85.png">

**Comment by cdparra** [comment]
Should be working now. This was a maintenance issue. The configuration in the database that establishes which fields are required was asking for a description field, but this does not exist. It should ask for the `text` field.
