### ISSUE TITLE
It is impossible to open a proposal in a new page

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#12]
Someone from LNA told me that when she is making a right click on a proposal and try to open it in a new page/window, 

It would be great to create this possibility

**Comment by cdparra** [comment]
Our current security model manages session in the scope of browser's tab to allow for multiple sessions in the same browser. We will review the security model and add the possibility of having a browser wide session in future releases, after we develop notifications and other more urgent components

**Comment by LucileMP** [comment]
Ok perfect ! It was an idea, and of course, not the most pressing issue :)
