### ISSUE TITLE
Prevent non-authors from editing Public Drafts

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#120]
Public Drafts can be viewed and commented on by all members of the Unifesp community but ONLY edited by authors (those who are Compartilhado).  Currently, I am not shared in the proposal below, created by Cristhian, but I can edit it.  This is incorrect.

Prevent non-authors from editing Public Drafts (and also Published Proposals).

![screen shot 2018-07-04 at 1 39 11 am](https://user-images.githubusercontent.com/5572598/42276746-39be19c4-7f6b-11e8-8604-9276cc9da70f.png)

**Comment by cdparra** [comment]
@jamesholston This is a problem with PeerDoc. As of now, if you can access a PD, and you are logged in into PD system, you will be able to edit it regardless because there are no permissions implemented. Even published PDs have this problem (I think)
