### ISSUE TITLE
Translate error message for status change to Public Drafts and Published

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#122]
Change error message in screenshot below to following  =>

"Para alterar o status para Rascunho Público ou Publicada, os itens Tema, Palavras-chave, Campus Proposta e Resumo são obrigatórios." 

This message applies to both Public Drafts and Published.

![screen shot 2018-07-04 at 10 42 12 am](https://user-images.githubusercontent.com/5572598/42280417-17f0b0c0-7f77-11e8-95c7-521b1263acec.png)

**Comment by cdparra** [comment]
This is now part of EPIC #118
