### ISSUE TITLE
Change Campaign Page short description

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#124]
Change Campaign Page short description to => 

Bem-vindxs à página da construção participativa do Projeto Pedagógico Institucional (PPI). Faça login para criar propostas, deliberar e contribuir para esse documento orientador da universidade.   

--  Adjust font so that it fits on two lines, instead of current three.

![image](https://user-images.githubusercontent.com/5572598/42520132-e8e33cf2-843b-11e8-81a9-3864a69ada94.png)

**Comment by cdparra** [comment]
You can already update this from the edit campaign page @jamesholston

About the adjusting to two lines, I would recommend against this type of change unless we do a redesign of the header. Your text could fit in two lines, but it will break the texts or other campaigns. So is better not to base our changes  on one instance of the content.
