### ISSUE TITLE
PeerDoc not rendering in new Public Draft in testing

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#132]
PeerDoc "not found" in a new Public Draft I just created in testing (first screenshot, Jul 14).  PeerDoc renders correctly in older Public Drafts (second screenshot, Jul 11).  The bug would thus appear to be related to last push to testing (on Jul 13)?

Return to Private Draft does not restore PeerDoc document, which is still "not found" (third screenshot).

1.  PeerDoc "not found" after change to Public Draft:
![screen shot 2018-07-14 at 1 19 14 am](https://user-images.githubusercontent.com/5572598/42720790-8aaada3e-8704-11e8-95d4-929b44780813.png)

2.  Older Public Draft rendering PD correctly:
![screen shot 2018-07-14 at 1 24 33 am](https://user-images.githubusercontent.com/5572598/42720799-c28ceb72-8704-11e8-998c-6c7c82ed2866.png)

3.  Return to Private Draft does not show PeerDoc:
![screen shot 2018-07-14 at 1 34 55 am](https://user-images.githubusercontent.com/5572598/42720898-99120276-8706-11e8-9297-02cd4bcb6a2c.png)

**Comment by cdparra** [comment]
The reason behind this issue is that the creator of some proposals is not in the list of authors of those proposals. Will be addressed by this issue: appcivist-platform#970 Creator is deleted from contribution_appcivist_author table
