### ISSUE TITLE
Change wording of logged-out alert message

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#133]
In message below, change "Iniciar Sessão" => "Fazer Login"

Se esta proposta está compartilhada com você, faça login para acessá-la ('Iniciar Sessão', acima). Se ela não está, peça a alguém listado para compartilhá-la com você e depois faça login.

![screen shot 2018-07-14 at 1 42 53 am](https://user-images.githubusercontent.com/5572598/42720928-404a97c4-8707-11e8-8083-7012ba6fab6b.png)

**Comment by cdparra** [comment]
Solved via hotfix
