### ISSUE TITLE
Logged-out view message shows on new proposal when logged into CP's account (production)

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#135]
1.  Logged-out view message appears in new proposals when logged into CP's account on production site.  I created two new proposals in this account and got the message both times.  Incorrect.

![screen shot 2018-07-15 at 4 30 59 pm](https://user-images.githubusercontent.com/5572598/42738104-9af8db24-8854-11e8-8702-8fdfb67c1782.png)

NOTE:  CP's proposal has a different time format that JH's or RO's. It uses 12h format, others use 24h format.  It seems that time format depends on language selection.  12h format appears only with US English and Paraguayan Spanish.  Others use 24h format.  Changing the language, however, did not affect logged-out message view.  I switched CP to Portuguese, created a new  proposal, got the 24h format, but also got the logged-out view message.

2.  This logged-out message does NOT appear in new proposals when logged into JH's account or RO's account:

![screen shot 2018-07-15 at 5 22 35 pm](https://user-images.githubusercontent.com/5572598/42738139-09e1ffd4-8855-11e8-9f1d-63c723c66808.png)

![screen shot 2018-07-15 at 5 21 40 pm](https://user-images.githubusercontent.com/5572598/42738142-147cd680-8855-11e8-92f3-a4caae6f653a.png)

3.  From CP's account, I shared the new proposal created (#1 above) with me (JH) to follow email notification path.  All aspects worked correctly: I got the email notification with the link; followed the link to the proposal page; got the correct logged-out view with correct message covering the peerdoc text; logged in and accessed the proposal which did NOT have the logged-out message.
![screen shot 2018-07-15 at 5 05 12 pm](https://user-images.githubusercontent.com/5572598/42738186-e4bf3f2c-8855-11e8-9008-f31a75087887.png)

![screen shot 2018-07-15 at 5 07 20 pm](https://user-images.githubusercontent.com/5572598/42738182-da106baa-8855-11e8-89dc-224ce8040b32.png)

It may be, therefore, that the bug of showing the logged-out message in a new proposal in CP's account has something to do specifically with his account.  If so, does this bug happen with other accounts?

NOTE:  I am labeling this issue as critical because it might affect other accounts in addition to CP's.

4.  When logged into my account (coordinator) and viewing proposals with filter Rascunhos de Proposta, most proposals show this logged-out message  below the peerdoc text (which is therefore visible and editable).  This view does not seem correct.

![screen shot 2018-07-15 at 5 53 09 pm](https://user-images.githubusercontent.com/5572598/42738355-e3c682e4-8858-11e8-84fd-bcb66966bfc6.png)

However, the new proposals I created in my own account (JH) and in RO's account do not show this message accessed through Rascunhos de Proposta filter:

![screen shot 2018-07-15 at 6 02 40 pm](https://user-images.githubusercontent.com/5572598/42738379-5dbaf274-8859-11e8-8c02-e92d3f870f88.png)

5.  The original proposal created in CP's account (#1 above) that showed the message does NOT show the message after it was shared with JH, accessed either by Compartilhado Comigo or Rascunhos de Proposta filters: 

![screen shot 2018-07-15 at 6 05 56 pm](https://user-images.githubusercontent.com/5572598/42738432-f2917d14-8859-11e8-81f4-df5419843b3a.png)

**Comment by cdparra** [comment]
Issue solved after latest push to production.
