### ISSUE TITLE
Coordinators not able to edit Summaries (production and testing)

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#137]
Coordinators should be able to edit Resumo in Private and Public Drafts but currently cannot (production and testing).  They are able to edit the other AppCivist fields.

![screen shot 2018-07-15 at 6 05 56 pm](https://user-images.githubusercontent.com/5572598/42738704-66293f7e-885e-11e8-9b81-866087be83f5.png)

**Comment by cdparra** [comment]
Will be addressed in sprint due by Jul 24 on appcivist-pb-client#1296 `Allow Coordinators to edit summaries`
