### ISSUE TITLE
Change logged-out message for Public Draft

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#138]
-- Change message to read:
“Esta proposta tem o status de Rascunho Público. Toda a comunidade Unifesp pode ver e comentar sobre um Rascunho Público, mas só quem está compartilhado pode editar. Se você faz parte dessa comunidade, faça login para acessar.

-- note: add "Unifesp"; Add last sentence.

![screen shot 2018-07-17 at 1 05 44 pm](https://user-images.githubusercontent.com/5572598/42830556-29177924-89c2-11e8-9a71-01a93cdae159.png)

**Comment by cdparra** [comment]
Done via hotfix 2e2e7619ca1af849a8d537d0d0e5a669d45c7d5e
