### ISSUE TITLE
Theme not showing in Public Draft (testing)

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#139]
Theme not showing in Public Draft for logged-in users who are not creators, share-with collaborators, or coordinators.  It does show in Public Draft for creators, share-with collaborators, and coordinators.

1.  Logged-in view of creator (JH) shows theme:

![screen shot 2018-07-17 at 1 28 33 pm](https://user-images.githubusercontent.com/5572598/42831916-0a900a9e-89c6-11e8-8d70-8355c8b2870e.png)

2.  Logged in view of same public draft for a user who is not a creator, share-with collaborator, or coordinator does not show theme:

![screen shot 2018-07-17 at 1 31 13 pm](https://user-images.githubusercontent.com/5572598/42831970-35ec8a82-89c6-11e8-86e1-48d80f52efae.png)

**Comment by cdparra** [comment]
Solved by commit https://github.com/socialappslab/appcivist-pb-client/commit/0f0b17526859bc179414e4a57a72fd7ec40b644e
