### ISSUE TITLE
Create a campaign - Le sport de Haut Niveau

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#14]
Hi @cdparra, 

I do not know how they manage to do so, but yesterday, they deleted the campaign Le Sport de Haut Niveau... 
We need this campaign to work again. Is it possible to do so ? 
We need it ASAP. 
And they want to have only one working group in this campaign, called "Le développement du sport de haut niveau". 

Please, If you can manage to create (recreate, make appear again, I do not know what clearly happen) before this afternoon (my afternoon, so in 4 hours), it will be great.

**Comment by cdparra** [comment]
I forgot to close this issue, which was solved last week. The problem was on the UPDATE of the campaign: when users update a campaign, which is available for COORDINATORS under the menu, the connection between the campaign and the timeline is erased. That's a bug that has been fixed now.
