### ISSUE TITLE
Make and mark Resumo as required to change to Public Draft

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#140]
(1)  Make Resumo required field to change to Public Draft.  It used to be but is no longer.
(2) Mark as required in red if not filled in when changing status.

Screenshot shows that both Campus and Resumo are empty but only Campus is flagged in red.

![screen shot 2018-07-17 at 3 05 08 pm](https://user-images.githubusercontent.com/5572598/42836961-f243da58-89d2-11e8-8aa2-921595637308.png)

**Comment by cdparra** [comment]
This will require a change in the backend. As of now, the text is stored with an empty value and the backend only checks if it is NULL.
