### ISSUE TITLE
About the second phase of LNA

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#15]
Hey @cdparra, 

Hey Christian, 

I talk with LNA and everything seems to be working well now except from the Etherpad. 
When I was talking about issues, It is more about design and the organization of the website, and that why I was telling you last week that we could talk about this later, it was not the most urgent at the moment. I saw that Melonnie send us a draft, I will make comment on this ! Sorry if there was some miunderstandings, it is my mistake :) 

At the end of June, they will launch the second phase about deliberation. They are going to add new user. The list of the account that need to be create is in the attached files. Can you prepare those user account for the end of next week ? 
Also, we will have a meeting with LNA on the 10th of July, about deliberation and voting. Do you think it is possible to go through with you on what the platform offers during those steps. 

- [x] I want to be sure that I can answer all of their questions, and the best way to do that is to talk to you. Do you think we can have a small online meeting (20 minutes) to review those steps next week ? 
It will be very nice of you 😊

We need your help to create new accounts :)

- [x] This one is urgent : frederic.roy@thouars-communaute.fr

- [x] All the e-mail adresses that are in the attached files, for the beginning of July (let's say for the 3 or4 :))

[Autres membres CTS-1.xlsx](https://github.com/socialappslab/appcivist/files/1101514/Autres.membres.CTS-1.xlsx)

**Comment by cdparra** [comment]
@LucileMP this is all done
