### ISSUE TITLE
UNIFESP Phase 3 Remaining Issues

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist#156]
There are a number of remaining issues for Phase 3 that you should address first.  I reordered them on the Google Doc page

https://docs.google.com/document/d/183T6vdnyAVz-SK8qPUDsz5inS3xdWVDSmX8pxDIcGW8/edit?usp=sharing

There are 9 items total, organized into three sets:  
A. Minor translation/word changes.  These are small issues but bother people.  

B. Orientation issues.  
There are three here, and I think they are important.  They require a bit of development time but should be relatively easy. 

C.  The card banner color scheme.  Least important but also not difficult.

**Comment by mitar** [comment]
Closing this for now. We are now working only on a small subset of issues.
