### ISSUE TITLE
Accessability of the working group

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#17]
Major issue : the one to solve ASAP. 

One of the campaign manager told me that HE was the only one to have the possibility to modify a proposal, and that the other members of the WG had just a reader access, and that it was a problem. 

I do not know if it is true or if it is just because they do not know how to properly use the platform, but could you check and try to solve this ? 
It could be the reason why only a few are using the platform.

They want to send emails tomorrow. Can you deal with this today ? :)

**Comment by cdparra** [comment]
@LucileMP can you tell me what WG you are referring to and who the users are?

**Comment by LucileMP** [comment]
They were not specific. I think it was in the campaign L'accès aux équipements sPORTIFS. And it is for all working groups. 

But like I was saying, I do not know if it is the truth or if they did not use the platform properly.

**Comment by cdparra** [comment]
@LucileMP we need more precise information to tackle this. The only thing I could do was to quickly check if all the members in WG's of that campaign have the proper roles, and they DO. I also did test for 2 users, and had no issue. Return to us when you have more details.
