### ISSUE TITLE
Issues in the comment display

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#19]
See on this screenshot : 

![capture gg](https://user-images.githubusercontent.com/28006117/28110694-785c2914-66f3-11e7-830c-db7a7a773b2d.JPG)

**Comment by cdparra** [comment]
@LucileMP I will put this on hold until we integrate the new designs, which include a new commenting widget.

**Comment by LucileMP** [comment]
Ok, 
Do you know when will this be ready ? (the new design), just to give them some info.

**Comment by cdparra** [comment]
I think the new designe will be released in batches. The first batch, including notifications, will be released mid-aug. Some of the new designs for the campaign page for the end of august (which is when new commenting components should be done)
