### ISSUE TITLE
Display issues 

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#20]
Both on presentation of the campaign/working group and in the proposal titles, sometimes there is a limitation of characters. If the title is too long, not everything appears on the card. LNA considers this as a bug and would like this issue solved. 

I put some screenshots: 
![bug](https://user-images.githubusercontent.com/28006117/28113103-973d5fd0-66fb-11e7-99af-0c6e770e44c1.jpg)
![bug 1](https://user-images.githubusercontent.com/28006117/28113102-973c3b46-66fb-11e7-86d5-31614ca74452.jpg)

Can you do something about it?

**Comment by cdparra** [comment]
@LucileMP these are minor issues that are related to how we display information that is longer that the placeholder. We will work on these in the next dev sprint and get it done by next week.

**Comment by LucileMP** [comment]
Perfect !
