### ISSUE TITLE
Change link to PPI campaign 2018

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#29]
On Assembly page, change link to current PPI campaign
-- Increase font size 
-- Add (CLIQUE AQUI)

![screen shot 2018-03-28 at 3 57 55 pm](https://user-images.githubusercontent.com/5572598/38050279-d8b6ecc6-32a0-11e8-9648-261fc1601d05.png)

**Comment by cdparra** [comment]
Done, will be available tonight, after the next update to the site. cc @jamesholston @Alissonor
