### ISSUE TITLE
Remove university name from login window

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#32]
Remove university name (Universidade Federal de São Paulo) below university logo (which already includes name).  Move logo down so that it is a bit closer to email text box. 

![screen shot 2018-03-28 at 6 03 01 pm](https://user-images.githubusercontent.com/5572598/38056349-a11d22dc-32b2-11e8-8793-6d9ba7965b0e.png)

**Comment by cdparra** [comment]
This would conflict with other instances. For example, in Asunción, this is the login modal: 
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/a077f7fd-c387-4882-a03a-4436a839b27f)

It would be better to redesign the logo, such that it does not include the name. 
cc @jamesholston @Alissonor

**Comment by cdparra** [comment]
is covered by #74
