### ISSUE TITLE
Login modal sometimes w/o logo

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#36]
Sometimes the login screen appears without logo.  Cannot reproduce this problem regularly but it happens with regularity.

![screen shot 2018-03-28 at 6 56 14 pm](https://user-images.githubusercontent.com/5572598/38059437-cb6016a8-32bc-11e8-87a4-88cad3492691.png)

**Comment by cdparra** [comment]
fixed as part of redesign
