### ISSUE TITLE
Campaign Timeline

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#38]
Change timeline as follows
Fase 1:  Ideias e Propostas Iniciais
Fase 2:  Agrupamento
Fase 3:  Propostas Temáticas
Fase 4:  Votação
Fase 5:  Compilação
Fase 6:  Conselhos

**Comment by cdparra** [comment]
@Alissonor @jamesholston this is done. In the future, you can do this directly from the Edit Campaign form.
