### ISSUE TITLE
List of small modifications 

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#4]
@cdparra - the campain "Le sport au féminin" as some small modifications requests :
- [x] In the working group "Développer la médiatisation du sport féminin", a question is missing : « Quelle(s) promotion(s) médiatique(s) et quelle(s) communication(s) pour le sport féminin ? »; Can you add it ? 

- [x] Suppress the working group "Développer la pratique sportive féminine"

About the platform : 
- [x] under propositions, when no proposals is publish it is written : Non proposals dans cet espace pour l’instant - This is incorrect in french - please translate : Pas de propositions dans cet espace pour le moment

**Comment by cdparra** [comment]
@LucileMP this is all done.

**Comment by LucileMP** [comment]
Could you create accounts for thos emails adress : 

-	Marie-Laure LAFFARGUE : manager@basket-landes.com
-	Frédéric ROY : frederic.roy@thouars-communaute.fr
-	Véronique BAURET : veronique.bauret@sfr.fr
-	P. HUDE : p.hude@orange.fr 

Thanks

**Comment by cdparra** [comment]
Sure! Which working groups should they be part of? Is any of them a coordinator?

**Comment by cdparra** [comment]
@LucileMP, check comment above

**Comment by LucileMP** [comment]
In the campaign le sport au féminin and all the working groups. I do not think so :)

**Comment by cdparra** [comment]
@LucileMP I forgot to report back to you that all these users were already created. I will send by email their password, which they should change once they login for the first time.
