### ISSUE TITLE
Change the updated user list (of test period)

### ISSUE THREAD

**Issue by Alissonor** [socialappslab/appcivist#46]
Please, we insert new users, on the list of coordinators and test users:
https://docs.google.com/spreadsheets/d/1_0AJlb5GVqTuJcjA2KIEh5E0UL8pwO4DzRPyJ4bOgVo/edit?usp=sharing

**Comment by cdparra** [comment]
this is done cc @jamesholston @Alissonor

**Comment by cdparra** [comment]
All new users have the same pasword assigned originally to th eothers
