### ISSUE TITLE
Impossible to add proposals

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#5]
@cdparra 

Something is not working right with the platform and the add a proposal option. When you save the new proposal you have created and you go on the working group, nothing appears. Same if you publish directly the proposal, it does not appear in the platform. 

I have this issue, and one user too, and I think it is the same for everyone.

**Comment by cdparra** [comment]
@LucileMP: can you post some screenshots or some details about what campaigns are having this problem?

**Comment by LucileMP** [comment]
I can not add screenshots because nothing appears :) Whenyou click on save, a green stuff says that it was correctly saved but we can not find it after. 

It was on Le sport au féminin campaign, but maybe it is appearing with the rest as well

**Comment by cdparra** [comment]
@LucileMP I will be posting the new version Today. I think this should be fixed then, but I would like to ask you nonetheless if you can do one more test, and then send me the details of the proposal you created: the title, the user you used to created, the campaign in which you created the proposal and what working group you have chosen to create the proposal. If you can do that Today, it would be ideal

**Comment by cdparra** [comment]
@LucileMP one more thing: I am thinking of a possibility for this problem that I would like you to check: make sure the proposal has the Working group field selected

![image](https://cloud.githubusercontent.com/assets/630150/25564908/5205e92c-2d8b-11e7-9794-152ea7c02614.png)

**Comment by cdparra** [comment]
@LucileMP I have been testing this and is working for me. I created the "Testing new proposal" in the campaign `Le sport de haut niveau`, under group `Le développement du Sport de haut niveau`, then I visit the WG  and the proposal is in the list. 

![image](https://cloud.githubusercontent.com/assets/630150/25565766/9e2139dc-2d9b-11e7-9397-a0cec9f11281.png)

Notice that by default proposals are created with status NEW, so they are light green. This indicates that only members of that working group can see the proposal, but the proposal will not be listed in the campaign page. If you want to see it in the campaign page, you have to open the menu of the proposal (in the proposal card => the cog wheel, or in the propsal page => the cog wheel) and then hit PUBLISH. The color will change to a darker green and then the proposal will be available in the campaign dashboard.

**Comment by cdparra** [comment]
@LucileMP I can't reproduce this error. It all works well for me. Can you precise the steps you followed to produce this error?

**Comment by LucileMP** [comment]
It is working now for me too ! :)
