### ISSUE TITLE
Add non-registered author to Idea and Proposal Templates

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#57]
When you add a non-registered author to "Authors" field in template, the new name does not appear in the list under "Idea Author(s) Complementary Information."  Thus you can't add any complementary information.  In the screen shot below, the added non-registered author is Don Quixote.

Adding a non-registered author here will not register that person on the site.  It will only establish that he/she is an author.  If the notification feature is working, then that person will receive an email saying that they were added and, if selected will receive future updates.  Hopefully, those notifications will motivate the person to register (if eligible).

![screen shot 2018-04-03 at 1 40 42 pm](https://user-images.githubusercontent.com/5572598/38262786-a6c6f3b6-3744-11e8-9d86-1f2f5dbba25f.png)

**Comment by cdparra** [comment]
@jamesholston let's remove the URGENT from this since we will not be using the form anymore at UNIFESP
