### ISSUE TITLE
Change Add Proposal to Create Proposal

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#59]
Change "Add Proposal" button to "Create Proposal" for Phase 1 only.
Portuguese = Criar Proposta

**Comment by cdparra** [comment]
I would advise against this change, because we don't support different button names for the different phases. Add Proposal always means Create Proposal. 

Instead, let's think of the button title that will always apply to this functionality, regardless of phase.  @jamesholston

**Comment by jamesholston** [comment]
Then let's call it "Create Proposal" for all phases because that is what is happening and Create is more interesting than Add.
