### ISSUE TITLE
Working groups disappear in the menu 

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#6]
@cdparra 

This is a strange issue, so I will try to discribe it the best that I can. 

1. You access the campaign 
2. Then, you open the menu and you select the working group
3. You are in the working group dashboard
4. You want to change of working group and you open the menu again 
5. No working group appears 
6. You need to go back to the campagn dashboard and then reopen the menu to have the list appearing

Conclusion : this is quite complicated :) 

In my opinion, this menu should be rethink because it is not the best for users :) But, we can talk about this later. For now, is it possible that when you are in a working group dashboard, the other working groups appears in the menu ?

**Comment by cdparra** [comment]
@LucileMP this is connected to Issue #3: the same basic error is making the system lose the information about the working groups once you enter the working group page. We have fixed this and a new version will be published over the weekend. I am merging several changes from developers from the last 2 weeks and that's the reason why I cannot push the update sooner. As soon as it is ready, you will receive a notification to test

**Comment by cdparra** [comment]
@LucileMP should be fixed now. Please, try, confirm and close the issue if it works.
