### ISSUE TITLE
PeerDoc does not load

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#67]
When I enter the pinned card on Campaign Page using my account "jholston@berkeley.edu" in either prodution or testing, PeerDoc does not load.  Nor does it load in the proposal card now displayed under Coordinator Working Group of which I am a member.  When I use Alisson's account ("rigitano@unifesp.br"), PeerDoc loads perfectly from both cards.  See also Issue #66.

It seems that the problem is absence/presence of profile photo.  I tried account ftduarte1996@gmail.com.  It failed to load PeerDoc from pinned card.  The account had no profile photo.  After I added one, PeerDoc loaded perfectly.

![screen shot 2018-04-06 at 1 02 12 pm](https://user-images.githubusercontent.com/5572598/38431527-e942c5c8-399a-11e8-8049-04a5935cfc6a.png)

**Comment by cdparra** [comment]
Fixed was pushed to testing and production. Closing.
