### ISSUE TITLE
Change timeline Fase 1 milestone

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#69]
Change Fase 1 milestone from "Ideias e Propostas Inicais" to "Propostas Iniciais" only

![screen shot 2018-04-06 at 3 24 59 pm](https://user-images.githubusercontent.com/5572598/38437731-ca736094-39ae-11e8-93f2-d8f0c1c4c781.png)

**Comment by cdparra** [comment]
@jamesholston @Alissonor you can do this yourself from the Campaign menu (cogwheel icon) => Edit. I am closing this.
