### ISSUE TITLE
Proposal creation page redesign

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#76]
Attached is redesign for proposal creation page.
1.  Tool bar: 
1.1  Move existing cogwheel here; in cogwheel dropdown, remove "Editar informação"; other functions under review
1.2  Delete "ideias de contribuição", "Histórico", and "comment symbol 0"
1.3  Reposition tool bar items as indicated
1.4  Add button [Seguir Proposta] as indicated
1.5  Add button [Status] as indicated; it is a dropdown with three links (private draft, public draft, published).  When selected, each link opens an alert message.  The message has two options: [Cancelar]  [Confirmar] 
(1) Rascunho Privado [Private Draft]
-- Alert message: Rascunho Privado significa que somente os autores podem ver, editar e comentar.  Tem certeza de que deseja este status?  [Cancelar]  [Confirmar] 
(2) Rascunho Público  [Public Draft]
-- Alert message:  Rascunho Público significa que toda a comunidade universitária pode ver e comentar mas somente os autores podem editar.  Tem certeza de que deseja este status?  [Cancelar]  [Confirmar] 
(3)  Proposta Publicada  [Published Proposal]
-- Alert message: Proposta Publicada significa que toda a comunidade universitária pode ver e comentar mas ninguém pode mais editar. Uma vez publicada, a proposta é encaminhada para a Assembleia Intercampi Editorial para ser incluída na próxima fase.  Tem certeza de que deseja este status?  [Cancelar]  [Confirmar] 
(4) When user selects [Confirmar], the orange "current status alert" registers selection.
1.6  Add [current status alert] in orange that is synced with [Status] selection and with [current status alert] in orange in PeerDoc document below.

2.  Title
-- Dummy text as indicated
-- Add edit pencil and functionality
-- Sync with PeerDoc title, "Escholha um título"

3.  Add button [+ Addicionar Autor]
-- List of LDAP users appears upon typing first letters of name. If possible, home campus appears with each name to facilitate selection among same names (campus is part of LDAP profile).
-- Ideally, added author receives an email notification, sent to AppCivist profile email.
-- Name and profile photo of added author appears in row to left of button.

4.  Activity links
-- Criado
-- Add "Última atividade"  (=last activity): refers to any change.  Sync with PeerDoc
-- Remove"Última atualização" 

5.  Tema
-- Add dropdown menu with list of 11 themes: Visão de Universidade / Universidade Pública e Direito à Educação / Universidade, Território e Sociedade / Universidade Crítica, Ética e Inovadora / Ensino-Aprendizagem / Formação de Educadores / Avaliação / Atração de Ingressantes, Taxa de Sucesso e Redimensionamento de Cursos / Redes de Colaboração Nacionais e Internacionais / Gestão Acadêmica e Estruturas Organizacionais / O Estudante Universitário no Sécula XXI
-- Add top menu text as indicated
-- Only one selection is allowed.
-- Support configuration to require 1 Tema for Public Draft and Published Proposal

6.  Palavras-chave
-- Add button [+ Addicionar]
-- Allow maximum of 3 keywords
-- Support configuration to require keywords for Public Draft and Published Proposal

7.  Campus Autor
-- Add text "Campus Autor"  (=author campus)
-- Add dropdown menu with list of all campus and Reitoria:  Baixada Santista, Diadema, Guarulhos, Osasco, Reitoria, São José dos Campos, São Paulo
-- Add top menu text as indicated
-- Allow multiple entries
-- Support configuration to require author campus for Public Draft and Published Proposal

8.  Campus Proposta
-- Add text "Campus Proposta"  (= proposal campus)
-- Add dropdown menu with list of all campus and Reitoria:  Baixada Santista, Diadema, Guarulhos, Osasco, Reitoria, São José dos Campos, São Paulo
-- Allow multiple entries
-- Always optional

9.  Instructions text box
-- Add Instructions text box as indicated
-- Use first few lines of instructions as preview ... Ler  mais  [Read more]
-- Ler mais opens modal window with full instructions (Do not use scroll bar as attachment indicates):

https://docs.google.com/document/d/11HZ4ws8ZHLG9msx9__kdMmDnE1ed_2amrr-q4867vdE/edit?usp=sharing

![screen shot 2018-04-25 at 6 12 32 pm](https://user-images.githubusercontent.com/5572598/39273115-4b18dca6-48b4-11e8-85ce-fa0532f801fb.png)

Link to Temas Geradores PPI Completo:
https://docs.google.com/document/d/184thlPoRII_Qb629bc28uzgAI5Pt-oyz7E73yLdjzKk/edit?usp=sharing

10.  Breve descrição
-- Add placeholder "Máxima de 125 palavras"
-- Add "pencil" edit function
-- Make text area adjustable to size of text

11.  PeerDoc embed issue
-- AppCivist is not embedded PeerDoc correctly.  Should not see header but only what is shown in attachment.  See issue #73.
-- Remove "Inicial" from Proposta Inicial

12.  Page issues
-- Need to flag which custom fields go in the proposal header.
-- Need to sync:  PeerDoc title with AppCivist title; PeerDoc activity with AppCivist "Last activity"; current status alert in both

![initial proposal page mockup 2018-04-12](https://user-images.githubusercontent.com/5572598/38756688-ba29c75e-3f40-11e8-8f5b-10c0519e7b78.png)

**Comment by cdparra** [comment]
Add theme(s) number limitation configuration to campaign
