### ISSUE TITLE
Editable PeerDoc document can be created without login

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#78]
Bug:  A new editable PeerDoc document can be created without login.  It should only be available after login.

To reproduce error:  unlogged-in campaign page > click on pinned card > PeerDoc "Documentos" > "Novo Documento" > editable new document.

This may be a moot point because PeerDoc is not embedding in AppCivist correctly.  See issue #73.  It may be that after resolving #73, the bug I note here will disappear.

![screen shot 2018-04-17 at 1 49 01 pm](https://user-images.githubusercontent.com/5572598/38885136-4e672a88-4248-11e8-9c63-192ccf3a6d98.png)

**Comment by mitar** [comment]
I do not think this is covered by #73.

**Comment by mitar** [comment]
This is an issue in PeerDoc. I opened: https://github.com/peer/doc/issues/74

**Comment by cdparra** [comment]
Closing this as it related to peerdoc
