### ISSUE TITLE
Impossible to add a file when adding a proposal

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#8]
Hello @cdparra, 

Someone noticed a little bug when using the platform. 

She tried to add a file when she was creating a proposal, it was possible to select your file and then it appeared in the box. See picture bellow : 

![capture files](https://cloud.githubusercontent.com/assets/28006117/25653695/5a994aa6-2fee-11e7-8ac6-0203505e80e0.JPG)

But after, when you try to click on Ajouter fichier, nothing happen. I try to saved the proposal and when you open it after, the files is not there. 

It is a small issue because you can add files when you are working on the proposal, but it is better if it is working in the add a proposal tool 

Thanks

**Comment by cdparra** [comment]
@LucileMP this issue will be addressed in the coming week (or during the first sprint of June if idea collection takes up all the development time)

It will be address in this development issue ref [appcivist-pb-client#624](https://github.com/socialappslab/appcivist-pb-client/issues/624)

**Comment by cdparra** [comment]
This should be fixed now. Please try @LucileMP
