### ISSUE TITLE
Add Research Consent to sign-up screen and store response

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist#86]
Add Research Consent to sign-up screen and store user response (agree/decline)

Text of Research Consent:
https://docs.google.com/document/d/1Uk5lgaQ7AKcv94lF2KY8uRfqUQEHd0zvk4O3gjpgzpA/edit?usp=sharing

Note:  Will substitute Portuguese version when ready.

**Comment by cdparra** [comment]
To support this we need

[ ][back] Extend the information model campaign to store a research consent text for the first time a user visits the campaign
[ ][back] Participation model connects the user and the campaign, to store his/her reply to the consent form and mark that the user has visited the campaign at least once
[ ][back] Endpoint to get participation in campaign for user
