### ISSUE TITLE
Add a button erase

### ISSUE THREAD

**Issue by LucileMP** [socialappslab/appcivist#9]
Just an idea to improve one tool of the platform. 

Now : When you are a working group and you want to erase some proposals (because it was a try or I do not know why...), you need to open the proposal and then click on the button and select erase. It is not possible to do it directly from the working group dashboard (in the menu where you can publish a proposal...)

In the futur I would like : that the erase option appears directly in this menu in the working group dashboard. Otherwise, I believe it is too complicated for users. 
![image](https://cloud.githubusercontent.com/assets/28006117/25653970/8fe09f4c-2fef-11e7-8857-e8575b08c806.png)

**Comment by cdparra** [comment]
@LucileMP this button is actually already available in the proposal page for COORDINATORS and authors of the proposal.

**Comment by cdparra** [comment]
@LucileMP moreover, I just found that there is a a problem in how contribution cards are rendered which causes the menu on the card not to be the same as the menu in the proposal page (they should). Basically, the contribution cards are being loaded before the campaign information is loaded, and we use the campaign timeline information to know if edition of a proposal should be allowed. We will fix this during this week. 

The official development ticket for this is [appcivist-pb-client#623](https://github.com/socialappslab/appcivist-pb-client/issues/623)

**Comment by cdparra** [comment]
Ok, this is done and merged on [PR/625](https://github.com/socialappslab/appcivist-pb-client/pull/625). Will be working on next release.
